def options(opt):
        opt.load('compiler_c')

def configure(conf):
        conf.load('compiler_c') 

def build(bld):
        bld.program(source='main.c', target='app', use='myshlib mystlib') 
        bld.stlib(source='a.c', target='mystlib', use='myobjects') 
        bld.shlib(source='b.c', target='myshlib') 
        bld.objects(source='c.c', target='myobjects')